### ISSUE TITLE
Method KaanTanis\FilamentPasswordConfirmation\Http\Livewire\Auth\PasswordConfirmation::put does not exist.

### ISSUE THREAD

**Issue by abdulmejidshemsu** [KaanTanis/filament-password-confirmation#3]
Method KaanTanis\FilamentPasswordConfirmation\Http\Livewire\Auth\PasswordConfirmation::put does not exist.

!! UPDATE file KaanTanis\FilamentPasswordConfirmation\Http\Livewire\Auth\PasswordConfirmation.php line 52 
FROM 
 $this->put('auth.filament_password_confirmed_at', time());
 TO
 session()->put('auth.filament_password_confirmed_at', time());

**Comment by KaanTanis** [comment]
forgotten new release. Thank you, now fixed.
