### ISSUE TITLE
Attempt to read property "password" on null

### ISSUE THREAD

**Issue by abdulmejidshemsu** [KaanTanis/filament-password-confirmation#4]
Attempt to read property "password" on null, check if the user logged in first

Update line 46 file 
To \KaanTanis\FilamentPasswordConfirmation\Http\Livewire\Auth\PasswordConfirmation.php

```
 if ($request->user() && !Hash::check($data['password'], $request->user()->password)) {
            throw ValidationException::withMessages([
                'password' => __('The provided password does not match your current password.'),
            ]);
        } 
```

**Comment by KaanTanis** [comment]
Actually the problem here is that the non-login user has to log in first. In other words, we need to restrict non-login users access to the confirmation page and redirect login first. I'm working on it now.

**Comment by abdulmejidshemsu** [comment]
yes you are correct but you just adding `$request->user()` before the hash check actually redirect it to the login page updating the code like below will redirect the user to the login page
```
 if ($request->user() && !Hash::check($data['password'], $request->user()->password)) {
            throw ValidationException::withMessages([
                'password' => __('The provided password does not match your current password.'),
            ]);
        }
```
